name: Build and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        arch: [x64]
        include:
          - os: macos-latest
            arch: arm64
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.x'

    - name: Build binaries
      run: |
        for build_config in "${{ matrix.os }}" "${{ matrix.arch }}"; do
          GOOS=$(echo $build_config | grep -i 'windows' && echo 'windows' || echo 'darwin')
          GOARCH=$(echo $build_config | grep -i 'arm64' && echo 'arm64' || echo 'x64')
          output_name="your_project_name_${GOOS}_${GOARCH}"
          go build -o ${{ github.workspace }}/${output_name}.
          echo "ASSET_NAME_${build_config}=${output_name}" >> $GITHUB_ENV
          echo "ASSET_PATH_${build_config}=${{ github.workspace }}/${output_name}" >> $GITHUB_ENV
        done

    - name: Generate unique tag name
      id: generate_tag
      run: |
        TAG_PREFIX=${{ github.ref_name }}
        DATE=$(date +%Y%m%d%H%M%S)
        UNIQUE_TAG="${TAG_PREFIX}_${DATE}"
        echo "TAG_NAME=${UNIQUE_TAG}" >> $GITHUB_ENV

    - name: Create or Update Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: Release ${{ env.TAG_NAME }}
        draft: false
        prerelease: false

    - name: Upload binaries to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: ${{ env.ASSET_NAME_${{ matrix.os }}_${{ matrix.arch }} }}
        asset_path: ${{ env.ASSET_PATH_${{ matrix.os }}_${{ matrix.arch }} }}
        asset_content_type: application/octet-stream
